### ISSUE TITLE
"Scroll to new posts" setting is silently ignored

### ISSUE THREAD

**Issue by UserNaem** [lewd-site/TinyIB#86] opened 2019-08-16 14:17 UTC
Unticking Settings > Posts > Scroll to new posts will occasionally still scroll to new posts; I don't have the exact STR, but this is what worked once:
Refresh.
Have someone post a reply.
Reply to their post.
Use J and K to navigate to your post.
The next time someone posts a reply, the board will auto-scroll to their reply.

**Comment by VVatashi** [comment] 2019-08-20 05:05
Can't reproduce

**Comment by UserNaem** [comment] 2019-08-20 10:01
Reproduced in Chrome/74.0.3729.172
Go to Settings > Posts and untick "Scroll to new posts"
Press RMB on the page and press Refresh
Open the reply form by using the quick reply button
Type a reply
Scroll up using the mouse wheel
Use Ctrl+Enter to send your reply
This will scroll to your reply.

**Comment by VVatashi** [comment] 2019-08-22 06:19
To disable scroll after posting you should also uncheck the "Scroll to the bottom after posting" option on the Form tab.

These settings will be merged, since it makes little sense to use them separately.

**Closed** 2019-09-02 05:12 UTC
